name: pyinstaller

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: prep
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv pyinstaller==6.3.0
          pipenv install
          rm -rf build dist
      - name: build
        shell: bash
        run: |
          pipenv --venv
          pipenv run pyinstaller run.py --hidden-import chkbit --hidden-import chkbit_cli --onefile --name chkbit --console --paths $(pipenv --venv)/lib/*/site-packages
          cat build/chkbit/warn-chkbit.txt
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: chkbit
          path: dist/chkbit
